#!/bin/bash

set -o errexit # Exit on error

bower cache clean
bower install
grunt execute:target

cd app/bower_components/modernizr
npm install
cd bin
modernizr --config ../../../../modernizr-config.json --dest ../../../../app/js/plugins/modernizr.js
